---
title: "Realisasi Sparepart 2020"
author: "Aris Warsito"
date: "2 April 2020"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Report Maret 2020  
Halaman ini berisi laporan ajuan dan realisasi sparepart periode maret 2020  
-------------------------------  
##   
### Tabel Ajuan dari User  


```{r include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
ajuan_03 <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQyzWENYo8j5mtMAgH04yoJ3ams0FdmeRrk5FikO93jq6g3__7iCm-c5nX9dP2WScA_h2Q_lOEFGOZU/pub?gid=0&single=true&output=csv")
realisasi_03 <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRmL2ZS3_Ai5yg9v55ZPIorZxTtZSuYApa4Ti2ut0i3FfBGb9Hr624WJidDWQalyWPWdGRzXiJtosLj/pub?gid=0&single=true&output=csv")

str(realisasi_03)
total_ajuan_03 <- ajuan_03 %>% 
                      group_by(NAMA.SEKSI.PLANNER) %>%
                      summarize(jumlah = sum(total, na.rm=TRUE))
format(total_ajuan_03$jumlah, big.mark=",",scientific=FALSE)                      
                                            
total_ajuan_03
                    
```
```{r, echo=FALSE, layout="l-body-outset"}
kable(total_ajuan_03, digits = 3, format.args = list(big.mark = ",", 
  scientific = FALSE)) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left", font_size = 10, fixed_thead = T) %>% 
  column_spec(2, bold = T, width = "8em", background = "#e8f0fe") %>%
  row_spec(0, background = "#617aa6", color = "white")



```
---------------------------------------------   
     
##   

### Daftar Jumlah Realisasi sparepart per unit kerja  
```{r include=FALSE}
realisasi_03$Amount.in.LC <- as.numeric(as.character(realisasi_03$Amount.in.LC))
total_realisasi_03 <- realisasi_03 %>% 
                      filter(NAMA.SEKSI.PG != "#N/A") %>%
                      group_by(NAMA.SEKSI.PG) %>%
                      summarize(jumlah = sum(Amount.in.LC, na.rm=TRUE))
format(total_realisasi_03$jumlah, big.mark=",",scientific=FALSE)                      
                                            
total_realisasi_03
```
  
  
```{r, echo=FALSE, layout="l-body-outset"}
kable(total_realisasi_03, digits = 3, format.args = list(big.mark = ",", 
  scientific = FALSE)) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left", font_size = 10, fixed_thead = T) %>% 
  column_spec(2, bold = T, width = "8em", background = "#e8f0fe") %>%
  row_spec(0, background = "grey", color = "white")

```  
  
    
--------------------------------------------------  

### Realisasi sparepart berdasarkan kategori aktivitas  

```{r, echo=FALSE}
by_kategori_03 <- realisasi_03 %>% 
                      
                      group_by(KATEGORI1) %>%
                      summarize(jumlah = sum(Amount.in.LC/1000000000, na.rm=TRUE)) 
                      
#format(by_kategori_03$jumlah, big.mark=",",scientific=FALSE)                      
                                            
g <- ggplot(by_kategori_03, aes(x = reorder(KATEGORI1, -jumlah), y = jumlah)) +
                  geom_bar(stat = "identity", fill="steelblue") +
                  
                  labs(y= "Jumlah dalam Milyar", x = "Kategori Aktivitas") +
                  coord_flip()
g
```

